### ISSUE TITLE
Mostrar dinheiro disponível na tela de compras

### ISSUE THREAD

**Issue by JoaoAPS** [Liebelts/gordura_simulator#13]
Quando entramos no mercado, o dinheiro que temos no bolso é mostrado.
Mas depois de selecionar a opção de fazer compras, nossa quantidade de dinheiro não é mais mostrada, fazendo que a gente tenha que lembrar quanto dinheiro tem.

Sugiro adicionar na função `compras` um print com a quantidade de dinheiro na carteira

**Comment by JoaoAPS** [comment]
Posso submeter um Pull Request se quiser

**Comment by oliebe** [comment]
adicionei :)
