### ISSUE TITLE
Sugestão de ideia

### ISSUE THREAD

**Issue by KairoMartins18** [Liebelts/gordura_simulator#17]
Volta cavernaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by oliebe** [comment]
naoooooooooooo
