### ISSUE TITLE
Bug do pao imperfeito

### ISSUE THREAD

**Issue by oliebe** [Liebelts/gordura_simulator#4]
quando come umas fatias de pao o numero vira uma dizima periodica. Se voce comer esse pedaco de pao com dizima seu peso tmb vira dizima, oq faz o jogo inteiro ser dizimado pois o peso é usado pra praticamente tudo
![](https://user-images.githubusercontent.com/42952107/66221102-aa6ff600-e6a4-11e9-94e1-9542d8b6422a.png)

**SO:**win7
**32 ou 64 bits** 32

**Comment by FlaviaBastos** [comment]
Oi, @Liebelts! Vou ver se consigo resolver esse bug, tá legal?

**Comment by oliebe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [a](https://trello.com/c/jM76toyL/8-a)
